name: BuildDocs

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  make_docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: python -m pip install sphinx sphinx-rtd-theme

    - run: python -m pip install -e .
      env:
        LW_CI_BUILD: true
        LW_DOCS: true

    - name: Build docs
      run: |
        cd docs
        make html
        touch _build/html/.nojekyll

    - name: Pack docs
      run: tar -cvf docs.tar docs/_build/html

    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs.tar

  deploy_docs:
    needs: make_docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    - uses: actions/download-artifact@v2
      with:
        name: docs
        path: NewDocs

    - name: Remove old and unpack docs
      run: |
        rm -r docs
        cd NewDocs
        tar -xvf docs.tar

    - name: Move docs
      run:  cp -a --verbose NewDocs/docs/_build/html docs

    - name: Commit docs
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add docs
        # This is a slightly messy line to only push if the commut succeeded
        # (because there was changes, but to not throw an error if there was no
        # changes.)
        (git commit -m "Autogenerated new docs" && git push) || true
